// <auto-generated />
using LearnWords.Model.DBEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnWords.Migrations
{
    [DbContext(typeof(ContextApp))]
    [Migration("20220618185841_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LearnWords.Model.DBEntity.Clases.FutureSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ENFutureContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENFuturePerfect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENFuturePerfectContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENFutureSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<int>("Succesful")
                        .HasColumnType("int");

                    b.Property<string>("UAFutureContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAFuturePerfect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAFuturePerfectContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAFutureSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ENFutureSimple" }, "FutureSentence_Index")
                        .IsUnique();

                    b.ToTable("FutureSentences");
                });

            modelBuilder.Entity("LearnWords.Model.DBEntity.Clases.PastSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ENPastContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENPastPerfect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENPastPerfectContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENPastSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<int>("Succesful")
                        .HasColumnType("int");

                    b.Property<string>("UAPastContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAPastPerfect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAPastPerfectContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAPastSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ENPastSimple" }, "PastSentence_Index")
                        .IsUnique();

                    b.ToTable("PastSentences");
                });

            modelBuilder.Entity("LearnWords.Model.DBEntity.Clases.PresentSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ENPresentContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENPresentPerfect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENPresentPerfectContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ENPresentSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<int>("Succesful")
                        .HasColumnType("int");

                    b.Property<string>("UAPresentContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAPresentPerfect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAPresentPerfectContinuous")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAPresentSimple")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ENPresentSimple" }, "PresentSentence_Index")
                        .IsUnique();

                    b.ToTable("PresentSentences");
                });

            modelBuilder.Entity("LearnWords.Model.DBEntity.Clases.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ENWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<string>("SecondForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Succesful")
                        .HasColumnType("int");

                    b.Property<string>("ThirdForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UAWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ENWord" }, "Word_Index")
                        .IsUnique();

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
